sudo: required
language: node_js
node_js:
  - 12

matrix:
  include:
  - os: osx
    osx_image: xcode9.4
    env: CC=clang CXX=clang++ npm_config_clang=1 MARKTEXT_IS_STABLE=1 MARKTEXT_EXIT_ON_ERROR=1
    compiler: clang
  - os: linux
    dist: bionic
    env: CC=clang CXX=clang++ npm_config_clang=1 MARKTEXT_IS_STABLE=1 MARKTEXT_EXIT_ON_ERROR=1 DISPLAY=:99.0
    compiler: clang
    services:
      - xvfb

cache:
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
  - "$HOME/.cache/yarn"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xvfb
    # atom/keyboard-layout
    - libx11-dev
    - libxkbfile-dev
    # atom/node-keytar
    - libsecret-1-dev
    # fontmanager
    - libfontconfig-dev
    # Build RPM on Ubuntu
    - rpm

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi

  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - source ~/.bashrc

  - $CC --version
  - $CXX --version
  - npm --version
  - yarn --version

  # Fix cache between Linux and macOS build workers.
  - rm -rf node_modules/vscode-ripgrep

  - yarn install --check-files --frozen-lockfile

script:
  - yarn run lint
  - yarn run validate-licenses

  # Unit and e2e tests
  - yarn run test

  # Build binaries
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then yarn run release:linux --publish always ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then yarn run release:mac --publish always ; fi

  # Calculate checksums
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum build/marktext-x64.tar.gz ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum build/marktext-x86_64.AppImage ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum build/marktext-*.deb ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sha256sum build/marktext-*.rpm ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shasum -a 256 build/marktext-mac.zip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then shasum -a 256 build/marktext.dmg ; fi

branches:
  only:
  - master
  - develop
  - /^release-v[0-9.]+(?:-[0-9a-zA-Z\.]+)?$/
